### ISSUE TITLE
Can't install with pip (python 2.7.13)

### ISSUE THREAD

**Issue by MartianH** [leonardoarroyo/django-google-address#1]
I tried installing this and I got a TypeError instead.

Full installation below:

```sh
Collecting django-google-address
  Using cached django-google-address-1.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-sZbUY5/django-google-address/setup.py", line 19, in <module>
        long_description=open('README.rst', encoding='utf-8').read(),
    TypeError: 'encoding' is an invalid keyword argument for this function
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-sZbUY5/django-google-address/
```

**Comment by leonardoarroyo** [comment]
Hello, Martian. Unfortunately, currently there's no Python 2 support. The module was developed and tested with Python 3.5 and Django 1.11.
I'll probably work on this this weekend to add Python 2.7 support and older versions of django as they're still widely adopted.
If you're willing to work on this push requests are also welcome :)

**Comment by MartianH** [comment]
Hi, thanks for the fast reply. I already suspected this was the case. I sadly do not have the time to help, but I wish you the best of luck. Though the only problems seems to be the way you encode the *README* for the long_description. Other than that it would probably work fine in python 2 (on first glance).
